### ISSUE TITLE
CLI config file not found under macOS

### ISSUE THREAD

**Issue by davlgd** [CleverCloud/clevercloud-client-go#7]
The client is using `xdg` to find where the `clever-tools.json` file is on the system. But it's using `SearchConfigFile()` for that. Thus, it's looking in `XDG_CONFIG_HOME`:

- ~/.config (Unix)
- ~/Library/Application Support (macOS)

But the `clever-tools.json`file is in `$HOME/.config/clever-cloud/` folder on both systems, so the file is not found if the user is using macOS (I didn't check for Windows).

**Comment by miton18** [comment]
`~/Library/Application Support (macOS)` seems the standard directory to store configurations on OSX.

Maybe the `clever-tools` use a tool library for XDG, https://www.npmjs.com/package/xdg?activeTab=code

https://github.com/CleverCloud/clever-tools/issues/655

**Comment by davlgd** [comment]
Even if the `clever-tools` are updated anytime soon, it will take some time for users to have a config file in the good folder. Maybe we can support the current situation in the meantime ?
